// <auto-generated />
using System;
using KrautSourceWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KrautSourceWebApi.Migrations
{
    [DbContext(typeof(KrautDbContext))]
    [Migration("20220521111058_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("KrautSourceWebApi.Models.Data", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConsumerType")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("InsertTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PositionidLocation")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TypeOfData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PositionidLocation");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("KrautSourceWebApi.Models.Location", b =>
                {
                    b.Property<string>("idLocation")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.HasKey("idLocation");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("KrautSourceWebApi.Models.Data", b =>
                {
                    b.HasOne("KrautSourceWebApi.Models.Location", "Position")
                        .WithMany()
                        .HasForeignKey("PositionidLocation");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
